var request = require('request');
var express = require('express');
var app = express();
var bodyParser = require('body-parser');

var stripe_apiKey = 'sk_live_O27jDXmAPTc8tDlAm9XfkzMn';
var firebase_authKey = '9ASbVVkN5TxYofSuifAQj2kzri9FJTUKfhPi1817';
var amount = 2500;

ops = {
  charge: function(args) {
    request.post({
      url: 'https://api.stripe.com/v1/charges',
      headers: {
        Authorization: 'Bearer ' + stripe_apiKey
      },
      form: {
        amount: amount,
        currency: 'usd',
        card: args.token,   // stripe charge token generated by stripe.js
        description: 'payment for open campus job post'
      }
    }, function (error, response, body) {
      var receipt = JSON.parse(body)  
      if (receipt.paid && receipt.amount >= amount) {
        args.job.paid = true;
        // mark the user as paid in firebase
        request.post({
          url: 'https://open-campus.firebaseio.com/jobs.json',
          qs: {auth: firebase_authKey},
          json: args.job
        });
      } else {
        return receipt; // error happened or user paid less, let client handle it
      }
    });
  }
};

app.all('*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  next();
 });

app.use(bodyParser());

app.post('/', function(request, response){
  response.send(ops.charge(request.body))
});

app.listen(3000);